mappings:
  BetterButtonAction: UncleCheese\BetterButtons\Actions\Action
  BetterButtonCancelAction: UncleCheese\BetterButtons\Actions\CancelAction
  BetterButtonCustomAction: UncleCheese\BetterButtons\Actions\CustomAction
  BetterButtonFrontendLinksAction: UncleCheese\BetterButtons\Actions\FrontendLinksAction
  BetterButtonLink: UncleCheese\BetterButtons\Actions\Link
  BetterButtonNestedForm: UncleCheese\BetterButtons\Actions\NestedForm
  BetterButtonPrevNextAction: UncleCheese\BetterButtons\Actions\PrevNextAction
  BetterButton: UncleCheese\BetterButtons\Buttons\Button
  BetterButton_Delete: UncleCheese\BetterButtons\Buttons\Delete
  BetterButton_New: UncleCheese\BetterButtons\Buttons\Create
  BetterButton_Publish: UncleCheese\BetterButtons\Buttons\Publish
  BetterButton_PublishAndAdd: UncleCheese\BetterButtons\Buttons\PublishAndAdd
  BetterButton_PublishAndClose: UncleCheese\BetterButtons\Buttons\PublishAndClose
  BetterButton_Rollback: UncleCheese\BetterButtons\Buttons\Rollback
  BetterButton_Save: UncleCheese\BetterButtons\Buttons\Save
  BetterButton_SaveAndAdd: UncleCheese\BetterButtons\Buttons\SaveAndAdd
  BetterButton_SaveAndClose: UncleCheese\BetterButtons\Buttons\SaveAndClose
  BetterButton_SaveAndNext: UncleCheese\BetterButtons\Buttons\SaveAndNext
  BetterButton_SaveAndPrev: UncleCheese\BetterButtons\Buttons\SaveAndPrev
  BetterButton_SaveDraft: UncleCheese\BetterButtons\Buttons\SaveDraft
  BetterButton_Unpublish: UncleCheese\BetterButtons\Buttons\Unpublish
  BetterButtonsCustomActionRequest: UncleCheese\BetterButtons\Controllers\CustomActionRequest
  BetterButtonsNestedFormRequest: UncleCheese\BetterButtons\Controllers\NestedFormRequest
  BetterButtonDataObject: UncleCheese\BetterButtons\Extensions\DataObjectExtension
  BetterButtonGroupable: UncleCheese\BetterButtons\Traits\Groupable
  GridFieldBetterButtonsItemRequest: UncleCheese\BetterButtons\Extensions\ItemRequest
  DropdownFormAction: UncleCheese\BetterButtons\FormFields\DropdownFormAction
  BetterButton_Versioned: UncleCheese\BetterButtons\Interfaces\BetterButtonVersioned
  BetterButtonInterface: UncleCheese\BetterButtons\Interfaces\BetterButtonInterface
