---
Name: betterbuttons
---
SilverStripe\ORM\DataObject:
  extensions:
    - UncleCheese\BetterButtons\Extensions\DataObjectExtension
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - UncleCheese\BetterButtons\Extensions\ItemRequest

BetterButtonsUtils:
  edit:
    prevNext: true
    create: true
  versioned_edit:
    prevNext: true
    create: true
  create:
    create: true

BetterButtonsActions:
  create:
    save: true
    saveAndClose: true

  edit:
    save: true
    saveAndClose: true
    delete: true
    frontendLinks: true

  versioned_edit:
    Group_Versioning: true
    frontendLinks: true

BetterButtonsGroups:
  SaveAnd:
    label: Save and...
    buttons:
      saveAndAdd: true
      saveAndClose: true
      saveAndNext: true
      saveAndPrev: true
  Versioning:
    label: Versioning...
    buttons:
      rollback: true
      unpublish: true
---
Only:
  classexists: SilverStripe\UserForms\Model\EditableFormField
---
SilverStripe\UserForms\Model\EditableFormField:
  better_buttons_versioned_enabled: false
---
Only:
  classexists: SilverStripe\UserForms\Model\EditableFormField\EditableOption
---
SilverStripe\UserForms\Model\EditableFormField\EditableOption:
  better_buttons_versioned_enabled: false
